// lib/preview.ts
import { createBrowserClient } from '@supabase/ssr';

export interface PreviewData {
  id?: string;
  title: string;
  html_content: string;
  css_content?: string;
  js_content?: string;
  preview_type?: 'website' | 'app';
  is_published?: boolean;
}

/**
 * Create a new preview
 */
export async function createPreview(data: PreviewData) {
  const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );

  // Get current user
  const { data: { user } } = await supabase.auth.getUser();
  
  if (!user) {
    throw new Error('User not authenticated');
  }

  const { data: preview, error } = await supabase
    .from('previews')
    .insert({
      user_id: user.id,  // ← CRITICAL: Add user_id explicitly
      title: data.title,
      html_content: data.html_content,
      css_content: data.css_content || '',
      js_content: data.js_content || '',
      preview_type: data.preview_type || 'website',
      is_published: data.is_published || false,
    })
    .select()
    .single();

  if (error) {
    console.error('Error creating preview:', error);
    throw error;
  }

  return preview;
}

/**
 * Update an existing preview
 */
export async function updatePreview(id: string, data: Partial<PreviewData>) {
  const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );

  const { data: preview, error } = await supabase
    .from('previews')
    .update({
      ...data,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id)
    .select()
    .single();

  if (error) {
    console.error('Error updating preview:', error);
    throw error;
  }

  return preview;
}

/**
 * Get a preview by ID
 */
export async function getPreview(id: string) {
  const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );

  const { data: preview, error } = await supabase
    .from('previews')
    .select('*')
    .eq('id', id)
    .single();

  if (error) {
    console.error('Error fetching preview:', error);
    throw error;
  }

  return preview;
}

/**
 * Get all previews for current user
 */
export async function getUserPreviews() {
  const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );

  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    throw new Error('User not authenticated');
  }

  const { data: previews, error } = await supabase
    .from('previews')
    .select('*')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching previews:', error);
    throw error;
  }

  return previews;
}

/**
 * Delete a preview
 */
export async function deletePreview(id: string) {
  const supabase = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );

  const { error } = await supabase
    .from('previews')
    .delete()
    .eq('id', id);

  if (error) {
    console.error('Error deleting preview:', error);
    throw error;
  }

  return true;
}

/**
 * Generate sample HTML for testing
 */
export function generateSampleHTML(title: string = 'Sample Website'): PreviewData {
  return {
    title,
    html_content: `
      <div class="container">
        <header class="header">
          <h1>${title}</h1>
          <nav>
            <a href="#home">Home</a>
            <a href="#about">About</a>
            <a href="#contact">Contact</a>
          </nav>
        </header>
        <main class="main">
          <section class="hero">
            <h2>Welcome to ${title}</h2>
            <p>This is a sample preview generated by WeVibeCode.ai</p>
            <button class="cta-button">Get Started</button>
          </section>
          <section class="features">
            <div class="feature-card">
              <h3>Feature 1</h3>
              <p>Amazing feature description</p>
            </div>
            <div class="feature-card">
              <h3>Feature 2</h3>
              <p>Another great feature</p>
            </div>
            <div class="feature-card">
              <h3>Feature 3</h3>
              <p>One more awesome feature</p>
            </div>
          </section>
        </main>
        <footer class="footer">
          <p>&copy; 2026 ${title}. All rights reserved.</p>
        </footer>
      </div>
    `,
    css_content: `
      body {
        margin: 0;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        color: #333;
        background: #f5f5f5;
      }
      .container {
        max-width: 1200px;
        margin: 0 auto;
        background: white;
        min-height: 100vh;
      }
      .header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        padding: 2rem;
      }
      .header h1 {
        margin: 0 0 1rem 0;
        font-size: 2rem;
      }
      .header nav {
        display: flex;
        gap: 1.5rem;
      }
      .header nav a {
        color: white;
        text-decoration: none;
        font-weight: 500;
        transition: opacity 0.2s;
      }
      .header nav a:hover {
        opacity: 0.8;
      }
      .main {
        padding: 2rem;
      }
      .hero {
        text-align: center;
        padding: 4rem 2rem;
        background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        border-radius: 1rem;
        margin-bottom: 3rem;
      }
      .hero h2 {
        font-size: 2.5rem;
        margin: 0 0 1rem 0;
        color: #2d3748;
      }
      .hero p {
        font-size: 1.25rem;
        color: #4a5568;
        margin: 0 0 2rem 0;
      }
      .cta-button {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border: none;
        padding: 1rem 2rem;
        font-size: 1.125rem;
        font-weight: 600;
        border-radius: 0.5rem;
        cursor: pointer;
        transition: transform 0.2s;
      }
      .cta-button:hover {
        transform: translateY(-2px);
      }
      .features {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        gap: 2rem;
      }
      .feature-card {
        background: white;
        border: 2px solid #e2e8f0;
        border-radius: 0.5rem;
        padding: 2rem;
        text-align: center;
        transition: all 0.3s;
      }
      .feature-card:hover {
        border-color: #667eea;
        box-shadow: 0 10px 25px rgba(102, 126, 234, 0.1);
        transform: translateY(-5px);
      }
      .feature-card h3 {
        margin: 0 0 1rem 0;
        color: #2d3748;
      }
      .feature-card p {
        margin: 0;
        color: #718096;
      }
      .footer {
        background: #2d3748;
        color: white;
        text-align: center;
        padding: 2rem;
        margin-top: 4rem;
      }
      .footer p {
        margin: 0;
      }
    `,
    js_content: `
      document.addEventListener('DOMContentLoaded', function() {
        const button = document.querySelector('.cta-button');
        if (button) {
          button.addEventListener('click', function() {
            alert('Button clicked! This preview is interactive.');
          });
        }
        
        // Add animation to feature cards
        const cards = document.querySelectorAll('.feature-card');
        cards.forEach((card, index) => {
          card.style.animationDelay = (index * 0.1) + 's';
        });
      });
    `,
    preview_type: 'website',
  };
}
